---
- name: Check if server is joined to the domain
  hosts: all
  gather_facts: no
  ignore_errors: true
  serial: 1
  vars:
    ansible_python_interpreter: /bin/python
  roles:
    - Check-DomainJoin
