---
- name: ESXi Post Build 1 Check - from USH
  hosts: all
  gather_facts: no
  ignore_errors: true
  serial: 1
  connection: local
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - include_tasks: ../roles/Check-ESXiPostBuild/tasks/esxilicense.yml
    - include_tasks: ../roles/Check-ESXiPostBuild/tasks/advancedsettings.yml
          
    - name: Process each ESXi host
      include_role:
        name: Check-ESXiPostBuild

