---
- name: ESXi Post Build Network Basic from USH
  hosts: all
  serial: 1
  gather_facts: no
  ignore_errors: true
  connection: local
  vars:
    ansible_python_interpreter: /bin/python
  roles:
    - ESXiPostBuildNetworkBasicLoop
