        - name: Is StorNext installed? checking the registry
          ansible.windows.win_powershell:
           script: |
            (gp HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*).DisplayName -Contains "StorNext File System"
           arguments:
           - -ExecutionPolicy
           - ByPass
          register: verifyreg
        - set_fact:
           verifyreg_var: "{{ verifyreg.output }}"
        - debug:
           var: verifyreg_var
          failed_when:
           - "False in verifyreg_var"

        - name: Checking installation folder
          win_stat:
           path: 'C:\Program Files\StorNext\bin\instsvc.exe'
          register: verifyfolder
        - set_fact:
           verifyfolder_var: "{{ verifyfolder.stat.exists }}"
        - debug:
           var: verifyfolder_var
          failed_when: verifyfolder.stat.exists == false

        - name: Confirming the version of StorNext File System
          ansible.windows.win_powershell:
           script: |
            function Get-StorNextApplicationVersion {
            $applicationName = "StorNext File System"
            $my_check = (gp HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*) | Select-Object DisplayName, DisplayVersion, InstallDate | Where -Property DisplayName -Match $applicationName
            $versionNumber = $my_check.DisplayVersion
            if ($my_check) {
            $versionNumber
            }
            else {
            write-warning "Application not found"
            }
            }
            Get-StorNextApplicationVersion
           arguments:
           - -ExecutionPolicy
           - ByPass
          register: verifyversion
        - set_fact:
           version_var: "{{ verifyversion.output }}"
#           cacheable: yes
#        - set_fact:
#           latestversion_var: "7.0.1"
        - debug:
           var: version_var
#          failed_when:
#           - "'7.0.1' or [] in version_var"
#          - version_var == "7.0.1"
        - fail:
           msg: Current version is up to date
          when: "'7.0.1' in version_var"

        - name: Create temp directory to install files
          ansible.windows.win_tempfile:
           state: directory
           path: C:\StorNextTemp

        - name: Copy StorNext install and other files
          ansible.windows.win_copy:
           src: files/7.0.1
           dest: C:\StorNextTemp

        - name: Install StorNext File System Version 7.0.1
          win_command: powershell.exe -ExecutionPolicy ByPass -File C:\StorNextTemp\7.0.1\stornextinstall.ps1

        - name: pause 15 seconds for installation to finish
          pause:
           seconds: 15

        - name: Confirm new version of StorNext File System
          ansible.windows.win_powershell:
           script: |
            function Get-StorNextApplicationVersion {
            $applicationName = "StorNext File System"
            $my_check = (gp HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*) | Select-Object DisplayName, DisplayVersion, InstallDate | Where -Property DisplayName -Match $applicationName
            $versionNumber = $my_check.DisplayVersion
            if ($my_check) {
            $versionNumber
            }
            else {
            write-warning "Application not found"
            }
            }
            Get-StorNextApplicationVersion
           arguments:
           - -ExecutionPolicy
           - ByPass
          register: verifyversionagain
        - set_fact:
           version2_var: "{{ verifyversionagain.output }}"
        - debug:
           var: version2_var

        - name: Remove Temp folder and files
          win_file:
           path: C:\StorNextTemp
           state: absent

        - name: Windows - Replace Windows Inventory File with Default Blank
          template:
           src: windows.j2
           dest: /var/ansible/WindowsStorNext
           owner: root
           group: root
           mode: 0644
          delegate_to: hynpl-ansbl-01v
